### ISSUE TITLE
Input value doesn't change on IE11

### ISSUE THREAD

**Issue by AustinLeeGordon** [escaladesports/synapse#16]
Input value doesn't change whenever typing in the search input on IE11.

**Website:** https://www.hutsoninc.com
**IE Version:** 11.0.9600.19002

**Error Stack:**
```
TypeError: Object doesn't support property or method 'assign'
   at value (http://www.hutsoninc.com/component---src-layouts-index-js-8816678e7841f2683230.js:10:29870)
   at changeTerm (http://www.hutsoninc.com/component---src-layouts-index-js-8816678e7841f2683230.js:11:15082)
   at i (http://www.hutsoninc.com/component---src-layouts-index-js-8816678e7841f2683230.js:11:7999)
   at o (http://www.hutsoninc.com/commons-88555be145814dcbd38f.js:4:23385)
   at zr.invokeGuardedCallback (http://www.hutsoninc.com/commons-88555be145814dcbd38f.js:6:25232)
   at zr.invokeGuardedCallbackAndCatchFirstError (http://www.hutsoninc.com/commons-88555be145814dcbd38f.js:6:25323)
   at c (http://www.hutsoninc.com/commons-88555be145814dcbd38f.js:4:24355)
   at p (http://www.hutsoninc.com/commons-88555be145814dcbd38f.js:4:24832)
   at y (http://www.hutsoninc.com/commons-88555be145814dcbd38f.js:4:24982)
   at d (http://www.hutsoninc.com/commons-88555be145814dcbd38f.js:4:24631)
```

**Comment by kennedyrose** [comment]
Sorry about that! It looks Object.assign needs to be polyfilled. I never caught it in the past because I always had it polyfilled before hand. I've made a note of this in the readme.

For Gatsby projects, the easiest way is a [polyfill.io plugin](https://www.npmjs.com/package/gatsby-plugin-polyfill-io). Installation that should fix it and stretch back support pretty far without any additional options or anything. Please let me know if it doesn't work for any reason.

**Comment by AustinLeeGordon** [comment]
Thank you! I'll give it a shot and let you know.

**Comment by AustinLeeGordon** [comment]
@kennedyrose Seems to work great! Thanks again!
